### ISSUE TITLE
new install - sensor not created

### ISSUE THREAD

**Issue by ofirmanor** [chaimchaikin/molad-hacs#7]
I am using HA 2025.4.4
I installed using HACS, then from the Integration page I added Molad Sensor, got a message it installed correctly.
However, there is no sensor
![Image](https://github.com/user-attachments/assets/50d75b08-f467-42af-bd18-7e4b6c593f91)
Looking at the log, i see` ModuleNotFoundError: No module named 'hdate.htables'`
Full error:
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/molad/sensor.py:5
integration: Molad Sensor (documentation, issues)
First occurred: 09:53:38 (1 occurrences)
Last logged: 09:53:38

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2640, in async_forward_entry_setup
    result = await self._async_forward_entry_setup(entry, domain, True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2671, in _async_forward_entry_setup
    await integration.async_get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1085, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1162, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1132, in async_get_platforms
    await self.hass.async_add_import_executor_job(
        self._load_platforms, platform_names
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1249, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1281, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/molad/sensor.py", line 5, in <module>
    from molad.helper import MoladHelper
  File "/usr/local/lib/python3.13/site-packages/molad/helper.py", line 5, in <module>
    import hdate.htables
ModuleNotFoundError: No module named 'hdate.htables'
```

**Comment by chaimchaikin** [comment]
Thanks for reporting! This should be resolved now in latest release: https://github.com/chaimchaikin/molad-ha/releases/tag/v0.5.0

**Comment by ofirmanor** [comment]
Thanks Haim!
I just tested 0.5 (removed previous version, restarted, did a clean install). Unfortunately, I still don't see entities, but the error in the log is now different, maybe HA is pulling a different module version than you expected?

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:382
integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 14:08:37 (2 occurrences)
Last logged: 14:08:48

Error while setting up molad platform for sensor: module 'hdate.converters' has no attribute 'jdn_to_hdate'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/molad/sensor.py", line 18, in async_setup_entry
    MoladSensor(hass),
    ~~~~~~~~~~~^^^^^^
  File "/config/custom_components/molad/sensor.py", line 67, in __init__
    BaseSensor.__init__(self, "molad", hass)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/molad/sensor.py", line 44, in __init__
    self.update_sensor()
    ~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/molad/sensor.py", line 71, in update_sensor
    m = self.molad.get_molad(d)
  File "/usr/local/lib/python3.13/site-packages/molad/helper.py", line 340, in get_molad
    molad = self.get_actual_molad(date)
  File "/usr/local/lib/python3.13/site-packages/molad/helper.py", line 160, in get_actual_molad
    d = self.get_next_numeric_month_year(date)
  File "/usr/local/lib/python3.13/site-packages/molad/helper.py", line 210, in get_next_numeric_month_year
    d = self.get_numeric_month_year(date)
  File "/usr/local/lib/python3.13/site-packages/molad/helper.py", line 201, in get_numeric_month_year
    h = hdate.converters.jdn_to_hdate(j)
AttributeError: module 'hdate.converters' has no attribute 'jdn_to_hdate'. Did you mean: 'jdn_to_gdate'?
```

**Comment by chaimchaikin** [comment]
> Thanks Haim! I just tested 0.5 (removed previous version, restarted, did a clean install). Unfortunately, I still don't see entities, but the error in the log is now different, maybe HA is pulling a different module version than you expected?
> 
> ```
> Logger: homeassistant.components.sensor
> Source: helpers/entity_platform.py:382
> integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
> First occurred: 14:08:37 (2 occurrences)
> Last logged: 14:08:48
> 
> Error while setting up molad platform for sensor: module 'hdate.converters' has no attribute 'jdn_to_hdate'
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in _async_setup_platform
>     await asyncio.shield(awaitable)
>   File "/config/custom_components/molad/sensor.py", line 18, in async_setup_entry
>     MoladSensor(hass),
>     ~~~~~~~~~~~^^^^^^
>   File "/config/custom_components/molad/sensor.py", line 67, in __init__
>     BaseSensor.__init__(self, "molad", hass)
>     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/molad/sensor.py", line 44, in __init__
>     self.update_sensor()
>     ~~~~~~~~~~~~~~~~~~^^
>   File "/config/custom_components/molad/sensor.py", line 71, in update_sensor
>     m = self.molad.get_molad(d)
>   File "/usr/local/lib/python3.13/site-packages/molad/helper.py", line 340, in get_molad
>     molad = self.get_actual_molad(date)
>   File "/usr/local/lib/python3.13/site-packages/molad/helper.py", line 160, in get_actual_molad
>     d = self.get_next_numeric_month_year(date)
>   File "/usr/local/lib/python3.13/site-packages/molad/helper.py", line 210, in get_next_numeric_month_year
>     d = self.get_numeric_month_year(date)
>   File "/usr/local/lib/python3.13/site-packages/molad/helper.py", line 201, in get_numeric_month_year
>     h = hdate.converters.jdn_to_hdate(j)
> AttributeError: module 'hdate.converters' has no attribute 'jdn_to_hdate'. Did you mean: 'jdn_to_gdate'?
> ```

thanks for the log, that actually seemed to have been the issue the first time round (new version of hdate module was being pulled in instead) and I pinned the version number to account for that. I'll have to experiment a bit here because in dev and on my own ha instance I can't replicate (it pulls correct module).

**Comment by Daniellamm** [comment]
@chaimchaikin Many of us are having this issue since we also use the HA "Jewish Calendar" addon which requires hdate 1.1.2

**Comment by chaimchaikin** [comment]
this should be resolved now with the latest release (v0.6.0), thank you for your patience :)
